{
 "title": "Services Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "device-api is_up",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"devices-api-scraper\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "devices-api cpu, %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "service_cpu_usage_percent{job=\"devices-api-scraper\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "devices-api mem_usage, %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "service_mem_usage_percent{job=\"devices-api-scraper\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "devices-api mem_usage, mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "service_mem_usage{job=\"devices-api-scraper\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "metrics-api is_up",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "up{job=\"metrics-api-scraper\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "metrics-api cpu, %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "service_cpu_usage_percent{job=\"metrics-api-scraper\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "metrics-api mem_usage, %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "service_mem_usage_percent{job=\"metrics-api-scraper\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "metrics-api mem_usage, mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "service_mem_usage{job=\"metrics-api-scraper\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rule-angine is_up",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "up{job=\"rule-engine-scraper\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rule-engine cpu, %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "service_cpu_usage_percent{job=\"rule-engine-scraper\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rule-engine mem_usage, %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "service_mem_usage_percent{job=\"rule-engine-scraper\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rule-engine mem_usage, mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "expr": "service_mem_usage{job=\"rule-engine-scraper\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}