global:
  scrape_interval: 5s

  external_labels:
    monitor: "iot-service"

rule_files:

scrape_configs:



#  - job_name: "prometheus"
#    dns_sd_configs:
#      - targets: ["prometheus:9090"]

  - job_name: "metrics-api-scraper"
    dns_sd_configs:
      - names:
          - 'metrics-api'
        type: 'A'
        port: 8000

  - job_name: "rule-engine-scraper"
    dns_sd_configs:
      - names:
          - 'rule-engine'
        type: 'A'
        port: 8000

  - job_name: "devices-api-scraper"
    dns_sd_configs:
      - names:
          - 'devices-api'
        type: 'A'
        port: 8000

#  - job_name: "rule-engine-scraper"
#    dns_sd_configs:
#      - targets: ["rule-engine:8000"]
#
#  - job_name: "devices-api-scraper"
#    dns_sd_configs:
#      - targets: ["devices-api:8000"]