name: highload-2025-ci

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker images
        run: docker compose build

  test:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip and install Poetry via pip
        run: |
          python -m pip install --upgrade pip

      - name: Install devices-api dependencies
        working-directory: ./devices-api
        run: |
          pip install -r requirements.txt

      - name: Install rule-engine dependencies
        working-directory: ./rule-engine
        run: |
          pip install -r requirements.txt

      - name: Install metrics-api dependencies
        working-directory: ./metrics-api
        run: |
          pip install -r requirements.txt

      - name: unit tests devices-api
        working-directory: ./devices-api
        env:
          PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
        run: |
          pytest --cov=src tests/

      - name: unit tests metrics-api
        working-directory: ./metrics-api
        env:
          PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
        run: |
          pytest --cov=src tests/

      - name: unit tests rule-engine
        working-directory: ./rule-engine
        env:
          PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
        run: |
          pytest --cov=src tests/

      - name: Integration tests
        env:
          PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
        run: |
          docker compose up -d rule-engine
          docker compose up -d metrics-api
          docker compose up -d devices-api
          docker compose up -d rule-engine
          docker compose up -d frontend
          docker compose up -d nginx
          docker compose logs -f &

          python integration_tests/test.py
